#!/bin/bash




# ---- main ----
case $1 in

	#option 1 : help
	'' | '-h' | '--help')
		echo "Usage : bashtools [option]"
		echo "Do something on Bash Tools."
		echo
		echo "Options :"
		echo "  -h, --help   : Show this help message."
		echo "  -s, --show   : Show all the available Bash Tools commands."
		echo "  -u, --update : Update Bash Tools to the latest version."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ -z $1 ]] && exit 1 || exit 0
	;;

	#option 2 : show
	'-s' | '--show')
		echo "Here is a list of the available Bash Tools :"
		list=$(fulls $HOME/.bash_tools | keep -f | keep -x)
		for l in ${list[@]}; do
			echo ' - '${l/"$HOME/.bash_tools/"/}
		done
	;;

	#option 3 : update
	'-u' | '--update')

		#go in bash_tools directory
		oldPath=$PWD
		cd $HOME/.bash_tools

		#get the latest version from GitHub (https://github.com/iasebsil83/Bash_Tools)
		git pull && {

			#success
			rm -f install
			echo "Bash tools updated !"
			cd $oldPath
		} || {

			#failure
			echo "bashtools: Could not update Bash tools.";
			cd $oldPath
			exit 1
		}

		#remove projia files (moved in $HOME directory. Use 'projia -u'  to update them)
		rm -rf $HOME/.bash_tools/.projia
	;;

	#undefined option
	*)
		echo "bashtools: Undefined option or argument '$1'."
		exit 1
	;;
esac
