#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'' | '-h' | '--help')
		echo "Usage : bashtools [action]"
		echo "Do something on Bash Tools."
		echo
		echo "Action :"
		echo "  -h, --help   : Show this help message."
		echo "  -s, --show   : Show all the available Bash Tools commands."
		echo "  -u, --update : Update Bash Tools to the latest version."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ $1 == '' ]] && exit 1 || exit 0
	;;

	#action 2 : show
	'-s' | '--show')
		echo "Here is a list of the available Bash Tools :"
		list=$(fulls $HOME/.bash_tools | keep -f | keep -x)
		for l in ${list[@]}; do
			echo ' - '${l/"$HOME/.bash_tools/"/}
		done
	;;

	#action 3 : update
	'-u' | '--update')

		#go in bash_tools directory
		oldPath=$(pwd)
		cd $HOME/.bash_tools

		#get the latest version from GitHub (https://github.com/iasebsil83/Bash_Tools)
		git pull && {
			#success
			#rm -f install
			echo "Bash tools updated !"
			cd $oldPath
		} || {
			#failure
			echo "bash_tools: Could not update Bash tools.";
			cd $oldPath
			exit 1
		}
	;;

	#undefined action
	*)
		echo "bashtools: Undefined action or argument '$1'."
		exit 1
	;;
esac
