#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'-h' | '--help')
		echo "Usage : find_dev [action]"
                echo "Helps you to know where a new device is added"
		echo "to your computer (in /dev)."
		echo
		echo "An alternative to this tools is running :"
		echo "        ls -ult /dev"
		echo "after having connected the device,"
		echo "and then compare the last access times."
                echo
                echo "Actions :"
                echo "  -h, --help : Show this help message."
                echo
                echo "This command is part of \"Bash Tools\"."
                echo "For more information about \"Bash Tools\", please check :"
                echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#undefined action
	-*)
		echo "find_dev: Undefined action '$1'."
		exit 1
	;;

	#action 2 : find dev process
	*)
		#get dev list BEFORE connection
		echo "Please ensure that the device to detect is not connected."
		read -p "Then press ENTER" temp
		before=$(ls /dev)

		#get dev list AFTER connection
		echo "Now connect the device."
		read -p "Then press ENTER" temp
		after=$(ls /dev)

		#compare the 2 lists
		new_dev_list=()
		new_dev_nbr=0
		echo "Here is the difference :"
		for a in ${after[@]}; do
			found=0
			for b in ${before[@]}; do
				if [[ $a == $b ]]; then
					found=1
				fi
			done
			if [[ $found == 0 ]]; then
				new_dev_nbr=$(($new_dev_nbr + 1))
				echo "New device detected : $a"
			fi
		done

		echo "Total : $new_dev_nbr new device(s) detected."
	;;
esac
