#!/bin/bash




# ---- EXECUTION ----

#fulls execution ($@:user arguments)
function fulls_exec() {

	#detect options and path
	include_hidden_files=0
	exclude_special=0
	path=''
	for arg in $@; do
		case $arg in

			#option 1 : include hidden files
			'-a' | '--all')
				include_hidden_files=1
			;;

			#option 2 : include hidden files except '.' and '..'.
			'-A' | '--All')
				include_hidden_files=1
				exclude_special=1
			;;

			#undefined option
			-*)
				echo "fulls: Undefined option '$arg'."
				exit 1
			;;

			#path found => stop analysing command
			*)
				path=$arg
				break
			;;
		esac
	done

	#special case : empty directory
	if [[ -z $path ]]; then
		isempty $PWD && exit 0
	else
		isempty $path && exit 0
	fi

	#path type
	case $path in

		#absolute path
		'/' | '/'*)

			#remove '/' at the end
			if [[ $path == *'/' ]]; then
				path_new_len=$(( ${#path} - 1 ))
				path=${path:0:$path_new_len}
			fi

			#include hidden files
			if [[ $include_hidden_files == 1 ]]; then
				for e in $path/.*; do
					if [[ $exclude_special == 0 || ($e != *'/.' && $e != *'/..') ]]; then
						echo "$e"
					fi
				done
			fi

			#regular files
			for e in $path/*; do
				echo "$e"
			done
		;;

		#relative or empty path given
		*)
			#directories
			if [[ -d $PWD/$path ]]; then

				#add '/' at the end
				if [[ ! -z $path && $path != *'/' ]]; then
					path=$path'/'
				fi

				#include hidden files (for directories only)
				if [[ $include_hidden_files == 1 ]]; then
					for e in $path'.'*; do
						if [[ $exclude_special == 0 || ($e != *'.' && $e != *'..') ]]; then
							echo "$PWD/$e"
						fi
					done
				fi

				#regular directories
				for e in $path*; do
					echo "$PWD/$e"
				done

			#files
			else
				echo "$PWD/$path"
			fi
		;;
	esac
}

#main
case $1 in

	#help
	'-h' | '--help')
		echo "Usage : fulls [option(s)] [path]"
		echo "Similar to 'ls' command : Lists all the files and folders existing in [path]"
		echo "                          with their full path (from /)."
		echo "                          If [path] is empty, the current directory is used."
		echo
		echo "Options :"
		echo "  -h, --help : Show this help message."
		echo "  -a, --all  : Include hidden files.              (similar to 'ls -a')"
		echo "  -A, --All  : Same as '-a' without '.' and '..'. (similar to 'ls -A')"
		echo
		echo "Examples : "
		echo "  > fulls ~"
		echo "  #list all current files & folders in $HOME with their full path."
		echo
		echo "  > fulls -A /usr/include"
		echo "  #list all current files & folders in /usr/include with their full path"
		echo "  #including hidden files."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#options
	'-a' | '--all' |   \
	'-A' | '--All')
		fulls_exec $@
	;;

	#undefined option
	-*)
		echo "fulls: Undefined option '$1'."
		exit 1
	;;

	#no option
	*)
		fulls_exec $@
	;;
esac
