#!/bin/bash



# Installation program for bash tools.
# This program removes itself when installation finished.
mv Bash_Tools ~/.bash_tools && \
echo -e "\n\n\n# Bash tools by I.A. :" >> ~/.bashrc && \
echo -e "PATH=\"\$PATH:~/.bash_tools\"\n\n\n" >> ~/.bashrc && \
rm ~/.bash_tools/install
