#!/bin/bash



# ---- keep shortcuts ----

#depending on mode ($1:index to seek, $2:mode)
function keep_mode() {

	#read standard input
	input=$(cat)

	#empty input is not to filter ('ls -dl' will work differently)
	if [[ ${input[@]} == '' ]]; then
		exit 0
	fi

	#get MODE info on file/folder
	for element in ${input[@]}; do
		info=$(ls -dl $element | cut -d ' ' -f 1)
		if [[ ${info:$1:1} == $2 ]]; then
			echo $element
		fi
	done
}



# ---- main ----
case $1 in

	#action 1 : help
	'' | '-h' | '--help')
		echo "Usage : keep [action]"
		echo "Reads standard input and output only a selection."
		echo
		echo "Actions :"
		echo "  -d, --directories : Keep only existing directories."
		echo "  -e, --exist       : Keep only existing files or directories."
		echo "  -f, --files       : Keep only existing files."
		echo "  -h, --help        : Show this help message."
		echo "  -r, --readable    : Keep only existing user readable files."
		echo "  -w, --writable    : Keep only existing user writable files."
		echo "  -x, --executable  : Keep only existing user executable files."
		echo
		echo "Example :"
		echo "  > ls -a | keep -d"
		echo "  #list all current files & folders but keeping only directories."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ $1 == '' ]] && exit 1 || exit 0
	;;

	#action 2 : directories only
	'-d' | '--directories')
		input=$(cat)
		for element in ${input[@]}; do
			if [[ -d $element ]]; then
				echo $element
			fi
		done
	;;

	#action 3 : existing only
	'-e' | '--exist')
		input=$(cat)
		for element in ${input[@]}; do
			if [[ -e $element ]]; then
				echo $element
			fi
		done
	;;

	#action 4 : files only
	'-f' | '--files')
		input=$(cat)
		for element in ${input[@]}; do
			if [[ -f $element ]]; then
				echo $element
			fi
		done
	;;

	#action 5 : user readable only
	'-r' | '--readable')
		keep_mode 1 r
	;;

	#action 6 : user writable only
	'-w' | '--writable')
		keep_mode 2 w
	;;

	#action 7 : user executable only
	'-x' | '--executable')
		keep_mode 3 x
	;;

	#undefined action
	-*)
		echo "keep: Undefined action '$1'."
		exit 1
	;;

	#no action => help with exit code
	*)
		keep
	;;
esac
