#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'-h' | '--help')
		echo "Usage : ls_complete [action] [path]"
                echo "Exactly the same thing as command 'ls' but with complete path output."
                echo
                echo "Action :"
                echo "  -h, --help : Show this help message."
                echo
                echo "Example : "
                echo "  > ls_complete ~"
                echo "  #list all current files & folders in $HOME with their full path."
                echo
                echo "This command is part of \"Bash Tools\"."
                echo "For more information about \"Bash Tools\", please check :"
                echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#undefined action
	-*)
		echo "ls_complete: Undefined action '$1'."
		exit 1
	;;

	#action 2 : ls with complete path
	*)
		#current directory
		if [[ $1 == '' ]]; then
			ls -d $PWD/*

		else
			#get both string and char array from $1
			dir_str=$1
			dir_arr=()
			while read -n1 c; do
				dir_arr+=($c)
			done <<< $1

			#remove '/' at the end
			lastIndex=$(( ${#dir_arr[@]} - 1 ))
			if [[ ${dir_arr[$lastIndex]} == '/' ]]; then
				dir_str=${dir_str:0:-1}
			fi

			#full path given (starts by '/')
			if [[ ${dir_str:0:1} == '/' ]]; then
				ls -d $dir_str/*

			#relative path given
			else
				ls -d $PWD/$dir_str/*
			fi
		fi
	;;
esac
