#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'-h' | '--help')
		echo "Usage : ls_complete [action] [path]"
                echo "Exactly the same thing as command 'ls' but with complete path output."
                echo
                echo "Action :"
                echo "  -h, --help : Show this help message."
                echo
                echo "Example : "
                echo "  > ls_complete ~"
                echo "  #list all current files & folders in $HOME with their full path."
                echo
                echo "This command is part of \"Bash Tools\"."
                echo "For more information about \"Bash Tools\", please check :"
                echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#undefined action
	-*)
		echo "ls_complete: Undefined action '$1'."
		exit 1
	;;

	#action 2 : ls with complete path
	*)
		#current directory
		if [[ $1 == '' ]]; then
			ls -d $PWD/*

		#full path given
		elif [[ ${1:0:1} == '/' ]]; then
			ls -d $1/*

		#relative path given
		else
			ls -d $PWD/$1/*
		fi
	;;
esac
