#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'-h' | '--help')
		echo "Usage : nbr [action]"
		echo "Read standard input and print the number of elements given."
		echo
		echo "Action :"
		echo "  -h, --help : Show this help message."
		echo
		echo "Examples : "
		echo "  > ls /usr/bin | nbr"
		echo "  #Shows how many files & folders exist in /usr/bin."
		echo
		echo "  > travelfs myDir echo CURRENT | keep -f | nbr"
		echo "  #Prints the number of files existing in directory 'myDir'"
		echo "  #and its sub-directories recursively."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#nothing => count words from stdin
	'')
		input=$(cat)
		nbr=0
		for e in ${input[@]}; do
			nbr=$(($nbr + 1))
		done
		echo $nbr
	;;

	#undefined action
	-*)
		echo "nbr: Undefined action '$1'."
		exit 1
	;;

	#anything else => help with exit code 1
	*)
		nbr -h
		exit 1
	;;
esac
