#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'' | '-h' | '--help')
		echo "Usage : pop [action] [file]"
		echo "Read a file & clear it (not removing it)."
		echo
		echo "Action :"
		echo "  -h, --help : Show this help message."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ $1 == '' ]] && exit 1
	;;

	#undefined action
	-*)
		echo "pop: Undefined action '$1'."
		exit 1
	;;

	#action 2 : pop file
	*)
		cat $1 && echo '' > $1 || {
			echo "pop: Unable to pop file '$1'."
			exit 1
		}
	;;
esac
