#!/bin/bash



# ---- MAIN ----
case $1 in

	#option 1 : help
	'' | '-h' | '--help')
		echo "Usage : pop [option] <file>"
		echo "Read a file & clear it (not removing it)."
		echo
		echo "Options :"
		echo "  -h, --help : Show this help message."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ -z $1 ]] && exit 1 || exit 0
	;;

	#undefined option
	-*)
		echo "pop: Undefined option '$1'."
		exit 1
	;;

	#option 2 : pop file
	*)
		cat $1 && echo '' > $1 || {
			echo "pop: Unable to pop file '$1'."
			exit 1
		}
	;;
esac
