#!/bin/bash



# ---- definitions ----
default_delay=0.1



# ---- utilities ----
function BIN_random() {
	if [[ $RANDOM -gt 16384 ]]; then
		echo -n 0
	else
		echo -n 1
	fi
}

function HEX_echoAsHex() { #($1:number between 1 and 16)
	n=$(($1-1))
	case $n in
		10) echo -n a ;;
		11) echo -n b ;;
		12) echo -n c ;;
		13) echo -n d ;;
		14) echo -n e ;;
		15) echo -n f ;;
		*) echo -n $n ;;
	esac
}

function HEX_checkLimit() { #($1:recursion number, $2:random number previously generated)

	#16 steps of 1536 ~> $RANDOM range
	limit=$(($1 * 2048))

	#check limit
	if [[ $2 -gt limit ]]; then
		HEX_checkLimit $(($1+1)) $2
	else
		HEX_echoAsHex $1
	fi
}

function HEX_random() {
	HEX_checkLimit 1 $RANDOM
}



# ---- main ----
case $1 in

	#action 1 : help
	'' | '-h' | '--help')
		echo "Usage : randsuite [action]"
                echo "Display a suite of random characters."
                echo
                echo "Action :"
                echo "  -b, --bin  [nbr]                   : Displays 0 or 1 randomly 'nbr' times."
		echo "                                       (leave 'nbr' empty for infinite loop)"
		echo "             [-d/--delay <delay>]      Delay between generation (default is 0.1s)."
		echo "             [-s/--separator [char]]   Separator between numbers."
		echo "                                       (default is NONE, leave empty for ' ')."
                echo "  -h, --help                         : Show this help message."
                echo "  -H, --hex  [nbr]                   : Displays 0 to f randomly 'nbr' times."
		echo "                                       (leave 'nbr' empty for infinite loop)"
		echo "             [-d/--delay <delay>]      Same thing as '-b'."
                echo "             [-s/--separator [char]]   Same thing as '-b'."
		echo
                echo "Examples : "
                echo "  > randsuite -b"
                echo "  #generates a binary random suite like 0110010010... indefinitely."
		echo
                echo "  > randsuite -H 5 -d 2"
                echo "  #generates 6 hexadecimal random numbers like d61af4 with 2s delay between numbers."
		echo
                echo "  > randsuite -b -d 1"
                echo "  #generates a random suite like 0110010010... indefinitely with 1s between numbers."
                echo
                echo "This command is part of \"Bash Tools\"."
                echo "For more information about \"Bash Tools\", please check :"
                echo "    https://github.com/iasebsil83/Bash_Tools"
		[[ $1 == '' ]] && exit 1
	;;

	#action 2 : binary suite
	'-b' | '--bin')
		case $2 in

			#no other arguments => infinite loop with standard delay
			'')
				while [[ 1 ]]; do BIN_random; sleep $default_delay; done
			;;

			#delay directly specified => infinite loop with custom delay
			'-d' | '--delay')
				while [[ 1 ]]; do BIN_random; sleep $3; done
			;;

			#iteration number specified => finite loop
			*)
				if [[ $3 == '-d' || $3 == '--delay' ]]; then
					[[ $4 == '' ]] && echo "randsuite: Action '-d' requires an argument." && exit 1

					#delay specified => finite loop with custom delay
					for randsuite_temp in $(seq $2); do
						BIN_random
						sleep $4
					done
				else

					#no delay specified => finite loop with default delay
					for randsuite_temp in $(seq $2); do
						BIN_random
						sleep $default_delay
					done
				fi
			;;
		esac
	;;

	#action 3 : hexadecimal suite
	'-H' | '--hex')
		case $2 in

			#no other arguments => infinite loop with standard delay
			'')
				while [[ 1 ]]; do HEX_random; sleep $default_delay; done
			;;

			#delay directly specified => infinite loop with custom delay
			'-d' | '--delay')
				while [[ 1 ]]; do HEX_random; sleep $3; done
			;;

			#iteration number specified => finite loop
			*)
				if [[ $3 == '-d' || $3 == '--delay' ]]; then
					[[ $4 == '' ]] && echo "randsuite: Action '-d' requires an argument." && exit 1

					#delay specified => finite loop with custom delay
					for randsuite_temp in $(seq $2); do
						HEX_random
						sleep $4
					done
				else

					#no delay specified => finite loop with default delay
					for randsuite_temp in $(seq $2); do
						HEX_random
						sleep $default_delay
					done
				fi
			;;
		esac
	;;

	#undefined action
	-*)
		echo "randsuite: Undefined action '$1'."
		exit 1
	;;
esac
