#!/bin/bash


#set number of colors per line (1st given argument)
if [[ ! -z $1 ]]; then
	nbr=$1
else
	nbr=10 #default value
fi



#display all possible colors
for i in {0..256}; do
	o=00$i
	if (( (i+1)%nbr == 0 )); then
		echo -ne "${o:${#o}-3:3}"$(tput setaf $i;tput setab $i)"   "$(tput sgr0)"\n"
	else
		echo -ne "${o:${#o}-3:3}"$(tput setaf $i;tput setab $i)"   "$(tput sgr0)"  "
	fi
done
echo ""
