#!/bin/bash



# ---- main ----
case $1 in

	#action 1 : help
	'-h' | '--help')
		echo "Usage : tput_colors [action] [nbr]"
		echo "Shows all the available colors in tput."
		echo "Argument 'nbr' is the number of colors to display per line."
		echo
		echo "Actions :"
		echo "  -h, --help : Show this help message."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#undefined action
	-*)
		echo "tput_colors: Undefined action '$1'."
		exit 1
	;;

	#action 2 : show all colors in tput
	*)
		#set number of colors per line (1st given argument)
		if [[ $1 == '' ]]; then
			nbr=10 #default value
		else
			nbr=$1
		fi

		#display all possible colors
		for i in {0..256}; do
			o=00$i
			if (( (i+1)%nbr == 0 )); then
				echo -ne "${o:${#o}-3:3}"$(tput setaf $i;tput setab $i)"   "$(tput sgr0)"\n"
			else
				echo -ne "${o:${#o}-3:3}"$(tput setaf $i;tput setab $i)"   "$(tput sgr0)"  "
			fi
		done
		echo
	;;
esac
