#!/bin/bash




# ---- EXECUTION ----

#main
case $1 in

	#help
	'-h' | '--help')
		echo "Usage : updateall [option]"
		echo "Update, upgrade, fix and clean all installed apt packages."
		echo
		echo "Options :"
		echo "  -h, --help : Show this help message."
		echo
		echo "This command is part of \"Bash Tools\"."
		echo "For more information about \"Bash Tools\", please check :"
		echo "    https://github.com/iasebsil83/Bash_Tools"
	;;

	#undefined option
	-*)
		echo "updateall: Undefined option '$1'." >&2
		exit 1
	;;

	#no option : update all
	*)

		#1) update
		echo -e "\nUpdating package list...\n"
		sudo apt update | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error updating packages list." >&2
			exit 1
		fi

		#2) full-upgrade
		echo -e "\nUpgrading packages...\n"
		sudo apt full-upgrade | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error upgrading packages." >&2
			exit 1
		fi

		#3) fix broken
		echo -e "\nFixing broken packages...\n"
		sudo apt install --fix-broken | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error fixing broken packages." >&2
			exit 1
		fi

		#4) fix missing
		echo -e "\nFixing missing packages...\n"
		sudo apt install --fix-missing | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error fixing missing packages." >&2
			exit 1
		fi

		#5) remove unused
		echo -e "\nRemoving unused packages...\n"
		sudo apt autoremove | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error removing unused packages." >&2
			exit 1
		fi

		#6) clean apt folders
		echo -e "\nCleaning all...\n"
		sudo apt autoclean | yes
		if [[ $PIPESTATUS[0] != 0 ]]; then
			echo "updateall: Error cleaning apt folders." >&2
			exit 1
		fi
		echo -e "\nAll packages have been updated."
	;;
esac
